// ============================================================
//  VTO Travel — Datos de Tours
//  Edita este archivo para actualizar la información de tours
// ============================================================

const TOURS = [
  {
    id: 1,
    nombre: "Tesoro de los Valles",
    subtitulo: "Hierve el Agua",
    horario: "8:30 am – 7:00 pm",
    precio: 500,
    descripcion: "Donde la naturaleza se convierte en piedra y maravilla.",
    emoji: "🌊",
    color: "#1a6eb5",
    lugares: [
      "Hierve el Agua",
      "Taller de Tapetes de lana en Teotitlán del Valle",
      "Taller de velas artesanales",
      "Fábrica de mezcal",
      "Árbol del Tule",
      "Zona arqueológica de Mitla",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía", "¡Degustación de mezcal GRATIS!"],
    recoleccion: "8:00 a 8:30 am",
    recomendacion: "Llevar ropa cómoda y desayunar antes de salir.",
    tags: ["Naturaleza", "Arqueología", "Mezcal"],
  },
  {
    id: 2,
    nombre: "La Grandeza Zapoteca",
    subtitulo: "Monte Albán",
    horario: "9:30 am – 5:30 pm",
    precio: 400,
    descripcion: "La grandeza zapoteca que domina los Valles Centrales.",
    emoji: "🏛️",
    color: "#c47a1e",
    lugares: [
      "Monte Albán",
      "Taller de alebrijes en San Antonio Arrazola",
      "Fábrica de mezcal ancestral",
      "Barro negro en San Bartolo Coyotepec",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía", "¡Degustación de mezcal GRATIS!"],
    recoleccion: "9:00 a 9:30 am",
    recomendacion: "Llevar ropa cómoda y desayunar antes de salir.",
    tags: ["Arqueología", "Arte", "Mezcal"],
  },
  {
    id: 3,
    nombre: "Sierra Norte",
    subtitulo: "Capulálpam de Méndez",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion: "Aventura, tradición y cultura en lo alto de la sierra.",
    emoji: "🏔️",
    color: "#2d7a3a",
    lugares: [
      "Ixtlán de Juárez",
      "Mirador de cristal",
      "Juegos extremos",
      "Capulálpam de Méndez",
      "Temazcal y medicina tradicional",
      "Las Ánimas",
      "Molenillos y chocolate artesanal",
      "San Pablo Guelatao",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar ropa abrigada, calzado cómodo, hidratación y protector solar.",
    tags: ["Aventura", "Naturaleza", "Cultura"],
  },
  {
    id: 4,
    nombre: "Cascadas y Misterios",
    subtitulo: "Río Peñas",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion: "Vive la mejor experiencia con nosotros entre cascadas y grutas.",
    emoji: "💧",
    color: "#1a8aa0",
    lugares: [
      "Peñas Gemelas",
      "Gruta",
      "Cascadas de Apoala",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar ropa cómoda, traje de baño y calzado adecuado.",
    tags: ["Aventura", "Naturaleza", "Cascadas"],
  },
  {
    id: 5,
    nombre: "Puerto Escondido",
    subtitulo: "Playas & Bioluminiscencia",
    horario: "5:30 am – 10:00 pm",
    precio: 700,
    descripcion: "Sol, mar y maravillas naturales en la costa oaxaqueña.",
    emoji: "🌊",
    color: "#1a5eb5",
    lugares: [
      "Playa Carrizalillo",
      "Playa Bacocho",
      "Liberación de tortugas",
      "Bioluminiscencia en Manialtepec",
      "Playa Zicatela",
      "Mercadito tradicional para desayunar",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "5:30 a 6:00 am",
    recomendacion: "Llevar traje de baño, muda adicional, sandalias, ropa cómoda.",
    tags: ["Playa", "Naturaleza", "Aventura"],
  },
  {
    id: 6,
    nombre: "Aventura en las Nubes",
    subtitulo: "Cumbre Tirolesa",
    horario: "8:15 am – 9:00 pm",
    precio: 700,
    descripcion: "Aventura en las nubes con paisajes de ensueño.",
    emoji: "🪂",
    color: "#7a1ab5",
    lugares: [
      "Senderismo en la cumbre",
      "Columpio al borde del abismo",
      "Temazcal (opcional)",
      "Tirolesa (opcional)",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar ropa abrigada, calzado cómodo, hidratación, protector solar y toalla si harán temazcal.",
    tags: ["Aventura", "Adrenalina", "Naturaleza"],
  },
  {
    id: 7,
    nombre: "Cenote & Grutas",
    subtitulo: "El Encanto",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion: "Aventura, tradición y cultura en lo alto de la sierra.",
    emoji: "🪨",
    color: "#1a8a6e",
    lugares: [
      "Grutas de San Sebastián de las Grutas",
      "Río subterráneo",
      "Cenote",
      "Ríos",
      "Mezcalería",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar traje de baño, sandalias, toalla y ropa cómoda.",
    tags: ["Aventura", "Naturaleza", "Mezcal"],
  },
  {
    id: 8,
    nombre: "Tour Alebrijes",
    subtitulo: "Magia Artesanal",
    horario: "9:30 am – 6:00 pm",
    precio: 700,
    descripcion: "Vive la magia de Oaxaca en cada artesanía.",
    emoji: "🐉",
    color: "#b51a5e",
    lugares: [
      "Barro Negro y Rojo",
      "Taller de Alebrijes",
      "Telar de Cintura",
      "Ex Convento de Santo Domingo",
      "Mercado de Ocotlán de Morelos",
    ],
    incluye: ["Pick-up en hotel o airbnb", "Seguro de viajero", "Coordinador de viaje", "Transporte redondo", "Guía"],
    recoleccion: "8:50 am y 9:30 am",
    recomendacion: "Llevar protector solar, ropa cómoda y fresca.",
    tags: ["Cultura", "Arte", "Artesanías"],
  },
];
